import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SnackbarProvider } from 'notistack'
import "./globals.css";
import Navbar from "@/components/Navbar";
import { AuthProvider } from "@/stores/auth/providers/auth.provider";
import NotificationProvider from "@/libs/notistack/notistack.provider";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "User Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className={inter.className} data-theme="cupcake">
      <body className="min-h-screen">
        <NotificationProvider>
          <AuthProvider>
            <Navbar />
            {children}
          </AuthProvider>
        </NotificationProvider>
      </body>
    </html>
  );
}
